# PUC-Rio
# INF2610 Real Time Rendering
# Bump Mapping
# Apr 25, 2016
# Author: Gabriel de Quadros Ligneul

target=app
cc=g++
opt=-O2
iflags=-I./lib
cflags=-Wall -Werror -std=c++11
lflags=-lGL -lGLEW -lglut
src=$(wildcard *.cpp)
obj=$(patsubst %.cpp,%.o,$(src))

all: $(target)

$(target): $(obj)
	$(cc) $(lflags) -o $@ $^

%.o: %.cpp
	$(cc) $(cflags) $(iflags) $(opt) -c -o $@ $<

depend: $(src)
	@$(cc) $(cflags) -MM $^
	
clean:
	rm -rf *.o $(target)

.PHONY: all depend clean

# Generated by `make depend`
lodepng.o: lodepng.cpp lodepng.h
main.o: main.cpp lodepng.h ShaderProgram.h Manipulator.h
Manipulator.o: Manipulator.cpp Manipulator.h
ShaderProgram.o: ShaderProgram.cpp ShaderProgram.h
